### ISSUE TITLE
[Registration Module Frontend] Prepare Sign up and Login Pages with Validation 

### ISSUE THREAD

**Issue by danthecm** [BuildForSDG/FASTA#10]
**Sign up Page**
The sign up pages should contain a form collecting details including 
- [x] Full Name
 - [x] Email 
- [x] Phone Number 
- [x] Password 
- [x] Confirm Password 

**Login Page**
Prepare Login page according to the UI design by Shammah 
**BOTH SIGN UP AND LOGIN PAGE SHOULD BE RESPONSIVE AND MOBILE FIRST**

**Comment by shammahk** [comment]
done
