### ISSUE TITLE
Create FASTA Database and Table 

### ISSUE THREAD

**Issue by danthecm** [BuildForSDG/FASTA#2]
**What is your feature request related to**
This is about creating the database and table for user registration

**Describe the solution you'd like**
A Cloud Based Database is going to be created named FASTA and a users table also which will contain list of registered users info using MongoDB.
The Basic users Table will hold information including
- [ ] Full Name
- [ ] Email
- [ ] Phone Number
- [ ] Password

**Comment by phawazzzy** [comment]
i am having difficulties connecting to the database, locally and atlas...
