### ISSUE TITLE
[DASHBOARD MODULE-2 (Frontend)]The header should contain button for profile, avatar for user, logo, search and consumes the relevant apis

### ISSUE THREAD

**Issue by myquery** [BuildForSDG/FASTA#28]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shammahk** [comment]
I've done this on the UI

**Comment by shammahk** [comment]
Please check the UI for updates
