### ISSUE TITLE
[SPLASH FRONTEND] Prepare Splash Screen and On boarding Pages 

### ISSUE THREAD

**Issue by danthecm** [BuildForSDG/FASTA#9]
**Create the Splash screen**
The Splash screen should be created in line with the UI design by Shammah 
https://xd.adobe.com/view/e3cad61b-397b-4f6b-62e1-937ca8d4c33b-95fb/

_On boarding pages should also be created giving uses highlights on what FASTA does_

**Comment by shammahk** [comment]
finished will create `PR` to `develop` soon
